services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_api
    environment:
      DATABASE_URL: mysql://symfony:symfony@db:3306/symfony_db?serverVersion=8.0.32&charset=utf8mb4
      APP_ENV: prod
    depends_on:
      - db
    networks:
      - proxy-net
    expose:
      - 9000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    depends_on:
      - backend
    networks:
      - proxy-net

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy-net

  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
      - ./backend/public:/var/www/html/public
      - ssl:/etc/nginx/ssl
      - nginx_cache:/var/cache/nginx
    depends_on:
      - backend
      - frontend
      #- maps
    networks:
      - proxy-net
  #maps:
  #  user: 1000:1000
  #  image: maptiler/tileserver-gl
  #  container_name: maps
  #  volumes:
  #    - ./maps_data:/data # aqu√≠ montas tus archivos .mbtiles
  #  networks:
  #    - proxy-net
  #  restart: always
  #  ports:
  #    - 8080:80
  #  command: ["--config", "/data/config.json", "--port", "80"]


volumes:
  db_data:
  node_cache: {}
  nginx_cache:
  ssl:
  #maps_data: {}

networks:
  proxy-net:
    external: true
